name: project_kepler
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  flutter_localizations: 
    sdk: flutter 
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  intl: ^0.17.0
  auto_route: ^6.0.5
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
flutter:
  uses-material-design: true
  generate: true