name: project_kepler
description: space launch tracker app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter 
  # State Management
  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  # Network
  dio: ^4.0.6
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  # Storage
  shared_preferences: ^2.0.15
  # Localization
  flutter_localizations:
    sdk: flutter
  # Navigation
  auto_route: ^6.0.5
  # Tools
  json_annotation: ^4.6.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  auto_route_generator: ^6.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
