name: project_kepler
description: space launch tracker app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.0.3
  flutter_bloc: ^8.1.1

  # Network
  dio: ^5.4.2+1
  google_sign_in: ^6.1.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5

  # Storage
  shared_preferences: ^2.0.15

  # Localization
  intl: ^0.18.0
  locale_emoji_flutter: ^0.2.1
  translator: ^1.0.0
  flutter_localizations:
    sdk: flutter

  # Navigation
  auto_route: ^6.0.5
  # Tools
  json_annotation: ^4.6.0
  connectivity_plus: ^3.0.4
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.0
  flutter_displaymode: ^0.6.0
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.1.0
  logger: ^2.2.0

  # UI
  google_fonts: ^6.1.0
  shimmer: ^2.0.0
  animate_gradient: ^0.0.2+1
  sheet: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  auto_route_generator: ^6.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env
