// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3emM4qscgPC9Gu_rpAUpKPdlEmiZRkc',
    appId: '1:600725819726:web:c68fc376c936da80c88e1f',
    messagingSenderId: '600725819726',
    projectId: 'project-kepler-2f046',
    authDomain: 'project-kepler-2f046.firebaseapp.com',
    storageBucket: 'project-kepler-2f046.appspot.com',
    measurementId: 'G-FVZMLSTXJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0PbOTD3dkrivnBqcosmFDjTWyjlzajwU',
    appId: '1:600725819726:android:707adc018d7d4366c88e1f',
    messagingSenderId: '600725819726',
    projectId: 'project-kepler-2f046',
    storageBucket: 'project-kepler-2f046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQTtuGeImbz4rvGQYAZXDD1fTqwGm06ug',
    appId: '1:600725819726:ios:4da63b69bb5edc84c88e1f',
    messagingSenderId: '600725819726',
    projectId: 'project-kepler-2f046',
    storageBucket: 'project-kepler-2f046.appspot.com',
    androidClientId:
        '600725819726-3foim9jof2nouv9tkr9bpbh6enackvu6.apps.googleusercontent.com',
    iosClientId:
        '600725819726-7n1nhreb5fv2qf5t0naq5o24ssspftji.apps.googleusercontent.com',
    iosBundleId: 'projectkepler.projectKepler',
  );
}
