// Mocks generated by Mockito 5.4.4 from annotations
// in project_kepler/test/unit/fetch_articles_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project_kepler/data/repositories/article_repository_impl.dart'
    as _i2;
import 'package:project_kepler/domain/entities/article.dart' as _i5;
import 'package:project_kepler/domain/use_cases/fetch_articles_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArticleRepositoryImpl_0 extends _i1.SmartFake
    implements _i2.ArticleRepositoryImpl {
  _FakeArticleRepositoryImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchArticlesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchArticlesUseCase extends _i1.Mock
    implements _i3.FetchArticlesUseCase {
  @override
  _i2.ArticleRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeArticleRepositoryImpl_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeArticleRepositoryImpl_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ArticleRepositoryImpl);

  @override
  _i4.Future<List<_i5.Article>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Article>>.value(<_i5.Article>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Article>>.value(<_i5.Article>[]),
      ) as _i4.Future<List<_i5.Article>>);
}
